server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: ash-expense-service
  data:
    mongodb:
      host: localhost
      username: root
      password: root
      port: 27017
      authentication-database: admin